import { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "engine",
    name: "Engine Parts",
    icon: "⚙️",
    subcategories: ["Pistons", "Gaskets", "Timing Belts", "Filters", "Oil Pumps"],
    count: 245,
    gradient: "from-orange-500 to-red-600",
  },
  {
    id: "brakes",
    name: "Brake System",
    icon: "🛑",
    subcategories: ["Brake Pads", "Disc Rotors", "Brake Fluid", "Calipers"],
    count: 189,
    gradient: "from-red-500 to-pink-600",
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "⚡",
    subcategories: ["Batteries", "Alternators", "Spark Plugs", "Wiring"],
    count: 312,
    gradient: "from-yellow-500 to-amber-600",
  },
  {
    id: "suspension",
    name: "Suspension",
    icon: "🏎️",
    subcategories: ["Shock Absorbers", "Springs", "Struts", "Ball Joints"],
    count: 156,
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "body",
    name: "Body Parts",
    icon: "🚗",
    subcategories: ["Bumpers", "Mirrors", "Headlights", "Fenders"],
    count: 428,
    gradient: "from-purple-500 to-violet-600",
  },
  {
    id: "exhaust",
    name: "Exhaust System",
    icon: "💨",
    subcategories: ["Mufflers", "Catalytic Converters", "Headers", "Pipes"],
    count: 98,
    gradient: "from-gray-500 to-slate-600",
  },
  {
    id: "accessories",
    name: "Accessories",
    icon: "✨",
    subcategories: ["Seat Covers", "Floor Mats", "Phone Mounts", "Dash Cams"],
    count: 567,
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "tools",
    name: "Tools & Garage",
    icon: "🔧",
    subcategories: ["Wrenches", "Jack Stands", "OBD Scanners", "Tool Kits"],
    count: 234,
    gradient: "from-cyan-500 to-sky-600",
  },
];

export const products: Product[] = [
  {
    id: "bp-001",
    name: "Ceramic Brake Pad Set - Front",
    description: "High-performance ceramic brake pads offering superior stopping power with minimal dust. Engineered for Indian driving conditions with excellent heat dissipation.",
    price: 2499,
    originalPrice: 3499,
    category: "brakes",
    subcategory: "Brake Pads",
    brand: "Brembo",
    images: ["/products/brake-pad-1.svg", "/products/brake-pad-2.svg"],
    rating: 4.7,
    reviews: 1243,
    inStock: true,
    features: ["Low dust formula", "Quiet operation", "OEM fitment", "Heat resistant up to 600°C"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Tata Nexon", "Honda City"],
    specifications: { Material: "Ceramic Compound", Position: "Front", Warranty: "30,000 km", Weight: "2.8 kg" },
    tags: ["bestseller", "top-rated"],
    badge: "bestseller",
  },
  {
    id: "oil-002",
    name: "Synthetic Engine Oil 5W-40 (5L)",
    description: "Fully synthetic engine oil with advanced additive technology. Provides maximum engine protection in extreme Indian weather conditions from -20°C to 50°C.",
    price: 3299,
    originalPrice: 4199,
    category: "engine",
    subcategory: "Filters",
    brand: "Mobil",
    images: ["/products/oil-1.svg", "/products/oil-2.svg"],
    rating: 4.8,
    reviews: 3567,
    inStock: true,
    features: ["API SN Plus certified", "Extended drain interval", "Superior engine cleanliness", "Fuel efficient"],
    compatibility: ["Universal - Petrol & Diesel"],
    specifications: { "Viscosity": "5W-40", "Volume": "5 Liters", "Type": "Fully Synthetic", "API Rating": "SN Plus" },
    tags: ["bestseller", "must-have"],
    badge: "bestseller",
  },
  {
    id: "sp-003",
    name: "Iridium Spark Plug Pack of 4",
    description: "Premium iridium spark plugs for enhanced fuel economy and smoother engine performance. Laser-welded iridium center electrode for 2x longer life.",
    price: 1899,
    originalPrice: 2499,
    category: "electrical",
    subcategory: "Spark Plugs",
    brand: "NGK",
    images: ["/products/spark-1.svg", "/products/spark-2.svg"],
    rating: 4.6,
    reviews: 892,
    inStock: true,
    features: ["Iridium tip", "Better fuel economy", "Easy start", "2x lifespan"],
    compatibility: ["Maruti Swift", "Hyundai Creta", "Tata Altroz", "Kia Sonet"],
    specifications: { "Electrode": "Iridium", "Thread Size": "M14x1.25", "Reach": "26.5mm", "Gap": "1.1mm" },
    tags: ["new"],
    badge: "new",
  },
  {
    id: "sa-004",
    name: "Monotube Shock Absorber Set - Rear",
    description: "Performance monotube gas-charged shock absorbers. Precision-tuned for Indian road conditions providing comfort and handling balance.",
    price: 8999,
    originalPrice: 12999,
    category: "suspension",
    subcategory: "Shock Absorbers",
    brand: "Bilstein",
    images: ["/products/shock-1.svg", "/products/shock-2.svg"],
    rating: 4.5,
    reviews: 456,
    inStock: true,
    features: ["Monotube design", "Gas charged", "Temperature stable", "Direct bolt-on"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Harrier", "MG Hector"],
    specifications: { "Type": "Monotube Gas", "Position": "Rear", "Length": "450mm", "Warranty": "50,000 km" },
    tags: ["trending"],
    badge: "trending",
  },
  {
    id: "acc-005",
    name: "Premium Leather Seat Cover Set",
    description: "Hand-stitched premium Nappa leather seat covers with memory foam padding. Custom-fit design for over 50 Indian car models.",
    price: 12999,
    originalPrice: 18999,
    category: "accessories",
    subcategory: "Seat Covers",
    brand: "AutoZone",
    images: ["/products/seats-1.svg", "/products/seats-2.svg"],
    rating: 4.9,
    reviews: 2100,
    inStock: true,
    features: ["Nappa leather", "Memory foam", "Water resistant", "Airbag compatible"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Honda City", "Tata Nexon"],
    specifications: { "Material": "Nappa Leather", "Padding": "Memory Foam", "Fit": "Custom", "Color": "Black/Red" },
    tags: ["premium"],
    badge: "bestseller",
  },
  {
    id: "bat-006",
    name: "AMG Performance Battery 72Ah",
    description: "High-cranking power battery with advanced lead-calcium technology. Designed to handle frequent start-stop traffic in Indian cities.",
    price: 5499,
    originalPrice: 6999,
    category: "electrical",
    subcategory: "Batteries",
    brand: "Exide",
    images: ["/products/battery-1.svg", "/products/battery-2.svg"],
    rating: 4.4,
    reviews: 1876,
    inStock: true,
    features: ["48-month warranty", "High cranking power", "Low maintenance", "Vibration resistant"],
    compatibility: ["Universal - 12V Vehicles"],
    specifications: { "Capacity": "72Ah", "Voltage": "12V", "Warranty": "48 months", "Technology": "Lead-Calcium" },
    tags: ["bestseller"],
    badge: "bestseller",
  },
  {
    id: "hl-007",
    name: "LED Headlight Kit H4 - 12000LM",
    description: "Ultra-bright LED headlight conversion kit with Cree chips. Plug-and-play installation with CANBUS compatibility.",
    price: 4299,
    originalPrice: 5999,
    category: "body",
    subcategory: "Headlights",
    brand: "Philips",
    images: ["/products/headlight-1.svg", "/products/headlight-2.svg"],
    rating: 4.7,
    reviews: 934,
    inStock: true,
    features: ["12000 lumens", "6000K white", "CANBUS ready", "50,000hr lifespan"],
    compatibility: ["Universal H4 fitment"],
    specifications: { "Lumens": "12,000 LM", "Color Temp": "6000K", "Power": "30W per bulb", "Lifespan": "50,000 hours" },
    tags: ["trending", "new"],
    badge: "new",
  },
  {
    id: "dash-008",
    name: "4K WiFi Dash Cam with GPS",
    description: "Ultra HD 4K front and rear dash camera with built-in GPS, night vision, and 24/7 parking surveillance mode.",
    price: 7999,
    originalPrice: 11999,
    category: "accessories",
    subcategory: "Dash Cams",
    brand: "70mai",
    images: ["/products/dashcam-1.svg", "/products/dashcam-2.svg"],
    rating: 4.6,
    reviews: 1567,
    inStock: true,
    features: ["4K recording", "GPS tracking", "Night vision", "App control"],
    compatibility: ["Universal - 12V"],
    specifications: { "Resolution": "4K 30fps", "FOV": "170°", "Storage": "Up to 256GB", "Connectivity": "WiFi + GPS" },
    tags: ["trending"],
    badge: "trending",
  },
  {
    id: "tb-009",
    name: "Timing Belt Kit with Water Pump",
    description: "Complete timing belt kit including belt, tensioner, idler pulleys, and water pump. Essential for engine longevity.",
    price: 6499,
    originalPrice: 8999,
    category: "engine",
    subcategory: "Timing Belts",
    brand: "Gates",
    images: ["/products/timing-1.svg", "/products/timing-2.svg"],
    rating: 4.5,
    reviews: 678,
    inStock: true,
    features: ["Complete kit", "OEM quality", "HNB rubber", "100,000km service life"],
    compatibility: ["Maruti Swift", "Hyundai Verna", "Honda Amaze"],
    specifications: { "Belt Type": "Toothed", "Material": "HNB Rubber", "Water Pump": "Aluminum", "Warranty": "60,000 km" },
    tags: [],
  },
  {
    id: "fm-010",
    name: "3D Custom Floor Mat Set (4 pcs)",
    description: "Premium 3D custom-fit floor mats with high-density foam backing. Waterproof and easy to clean with anti-slip design.",
    price: 3499,
    originalPrice: 4999,
    category: "accessories",
    subcategory: "Floor Mats",
    brand: "3D Mats",
    images: ["/products/floormat-1.svg", "/products/floormat-2.svg"],
    rating: 4.8,
    reviews: 2345,
    inStock: true,
    features: ["Custom 3D fit", "Waterproof", "Anti-slip", "Easy to clean"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Nexon"],
    specifications: { "Material": "XPE Foam", "Pieces": "4", "Waterproof": "Yes", "Color": "Black" },
    tags: ["bestseller"],
    badge: "bestseller",
  },
  {
    id: "cat-011",
    name: "Sports Catalytic Converter - BS6",
    description: "High-flow sports catalytic converter compliant with BS6 norms. Improves exhaust flow by 30% for better performance.",
    price: 15999,
    originalPrice: 19999,
    category: "exhaust",
    subcategory: "Catalytic Converters",
    brand: "Simota",
    images: ["/products/catconv-1.svg", "/products/catconv-2.svg"],
    rating: 4.3,
    reviews: 234,
    inStock: true,
    features: ["BS6 compliant", "High flow", "Stainless steel", "Direct replacement"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Tata Altroz"],
    specifications: { "Material": "Stainless Steel 304", "Compliance": "BS6", "Flow Increase": "30%", "Warranty": "24 months" },
    tags: ["performance"],
  },
  {
    id: "obd-012",
    name: "Professional OBD2 Scanner with Live Data",
    description: "Advanced OBD2 diagnostic scanner with live data streaming, freeze frame, and I/M readiness. Bluetooth enabled with smartphone app.",
    price: 3999,
    originalPrice: 5499,
    category: "tools",
    subcategory: "OBD Scanners",
    brand: "Innova",
    images: ["/products/obd-1.svg", "/products/obd-2.svg"],
    rating: 4.7,
    reviews: 1123,
    inStock: true,
    features: ["Live data", "Bluetooth 5.0", "Freeze frame", "I/M readiness"],
    compatibility: ["All OBD2 vehicles (2008+)"],
    specifications: { "Protocol": "OBD2/EOBD", "Connectivity": "Bluetooth 5.0", "App": "iOS & Android", "Update": "Lifetime free" },
    tags: ["trending"],
    badge: "trending",
  },
  {
    id: "bp-013",
    name: "Disc Brake Rotor - Front Pair",
    description: "High-carbon cast iron brake rotors with precision machining. Superior heat dissipation and reduced brake fade for spirited driving.",
    price: 3999,
    originalPrice: 5499,
    category: "brakes",
    subcategory: "Disc Rotors",
    brand: "Brembo",
    images: ["/products/p13-1.svg", "/products/p13-2.svg"],
    rating: 4.6,
    reviews: 567,
    inStock: true,
    features: ["High carbon content", "Precision machined", "Coated edges", "Direct fit"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Tata Nexon", "Honda City"],
    specifications: { Material: "High Carbon Iron", Diameter: "280mm", Thickness: "22mm", Ventilation: "Vented" },
    tags: ["performance"],
    badge: "trending",
  },
  {
    id: "oil-014",
    name: "Synthetic Engine Oil 0W-20 (4L)",
    description: "Ultra-low viscosity synthetic oil for modern hybrid and turbocharged engines. Maximum fuel efficiency with superior protection.",
    price: 2899,
    originalPrice: 3699,
    category: "engine",
    subcategory: "Engine Oil",
    brand: "Castrol",
    images: ["/products/p14-1.svg", "/products/p14-2.svg"],
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    features: ["0W-20 viscosity", "Hybrid compatible", "Fuel saving", "Low volatility"],
    compatibility: ["Toyota Camry Hybrid", "Honda Accord Hybrid", "Maruti Grand Vitara"],
    specifications: { "Viscosity": "0W-20", "Volume": "4 Liters", "Type": "Fully Synthetic", "API Rating": "SP" },
    tags: ["new", "eco-friendly"],
    badge: "new",
  },
  {
    id: "sp-015",
    name: "Platinum Spark Plug Pack of 4",
    description: "Platinum-tipped spark plugs for reliable ignition and extended service intervals. Ideal for older vehicles requiring standard replacement.",
    price: 899,
    originalPrice: 1299,
    category: "electrical",
    subcategory: "Spark Plugs",
    brand: "Bosch",
    images: ["/products/p15-1.svg", "/products/p15-2.svg"],
    rating: 4.5,
    reviews: 2341,
    inStock: true,
    features: ["Platinum tip", "100k km life", "Anti-corrosion", "Pre-gapped"],
    compatibility: ["Maruti Alto", "Hyundai Santro", "Tata Tiago", "Renault Kwid"],
    specifications: { "Electrode": "Platinum", "Thread Size": "M14x1.25", "Reach": "19mm", "Gap": "0.9mm" },
    tags: ["budget", "maintenance"],
    badge: "sale",
  },
  {
    id: "sa-016",
    name: "Front Strut Mount Kit",
    description: "Complete strut mount assembly with bearing and dust cover. Restores steering precision and eliminates suspension noise.",
    price: 2499,
    originalPrice: 3499,
    category: "suspension",
    subcategory: "Strut Mounts",
    brand: "Monroe",
    images: ["/products/p16-1.svg", "/products/p16-2.svg"],
    rating: 4.4,
    reviews: 789,
    inStock: true,
    features: ["Integrated bearing", "Dust cover included", "OE quality", "Easy installation"],
    compatibility: ["Hyundai i10", "Kia Picanto", "Maruti Celerio", "Tata Tigor"],
    specifications: { "Type": "Front Strut Mount", "Bearing": "Sealed", "Material": "Reinforced Rubber", "Warranty": "24 months" },
    tags: ["maintenance"],
    badge: "sale",
  },
  {
    id: "acc-017",
    name: "Wireless Car Charger Mount",
    description: "15W fast wireless charging with automatic clamping. Qi-certified with foreign object detection and overheating protection.",
    price: 2199,
    originalPrice: 2999,
    category: "accessories",
    subcategory: "Phone Mounts",
    brand: "Spigen",
    images: ["/products/p17-1.svg", "/products/p17-2.svg"],
    rating: 4.8,
    reviews: 3456,
    inStock: true,
    features: ["15W fast charge", "Auto-clamp", "Qi certified", "360° rotation"],
    compatibility: ["Universal - Qi enabled phones"],
    specifications: { "Output": "15W Max", "Input": "QC 3.0 / PD", "Mount": "Dashboard/Vent", "Certification": "Qi 1.3" },
    tags: ["bestseller", "tech"],
    badge: "bestseller",
  },
  {
    id: "bat-018",
    name: "EFB Start-Stop Battery 60Ah",
    description: "Enhanced Flooded Battery designed for vehicles with start-stop technology. Superior charge acceptance and cycle life.",
    price: 4799,
    originalPrice: 5999,
    category: "electrical",
    subcategory: "Batteries",
    brand: "Amaron",
    images: ["/products/p18-1.svg", "/products/p18-2.svg"],
    rating: 4.5,
    reviews: 1123,
    inStock: true,
    features: ["EFB technology", "Start-stop ready", "2x cycle life", "Maintenance free"],
    compatibility: ["Hyundai Venue", "Kia Sonet", "Maruti Brezza", "Tata Punch"],
    specifications: { "Capacity": "60Ah", "Type": "EFB", "CCA": "540A", "Warranty": "42 months" },
    tags: ["start-stop"],
    badge: "trending",
  },
  {
    id: "hl-019",
    name: "Fog Light Kit LED - Yellow",
    description: "3000K yellow LED fog lights for superior visibility in rain, fog, and dust. Plug-and-play with CANBUS decoder.",
    price: 2899,
    originalPrice: 3999,
    category: "body",
    subcategory: "Fog Lights",
    brand: "Osram",
    images: ["/products/p19-1.svg", "/products/p19-2.svg"],
    rating: 4.6,
    reviews: 876,
    inStock: true,
    features: ["3000K yellow", "IP68 waterproof", "CANBUS ready", "30,000hr life"],
    compatibility: ["Universal H8/H11/H16"],
    specifications: { "Color Temp": "3000K", "Lumens": "4000 LM", "Power": "25W", "Beam": "Wide flood" },
    tags: ["weather"],
    badge: "new",
  },
  {
    id: "dash-020",
    name: "Dual Channel Dash Cam 2K+1080p",
    description: "Front 2K and rear 1080p recording with GPS, WiFi, and supercapacitor. Voice control and ADAS alerts.",
    price: 6499,
    originalPrice: 8999,
    category: "accessories",
    subcategory: "Dash Cams",
    brand: "DDPAI",
    images: ["/products/p20-1.svg", "/products/p20-2.svg"],
    rating: 4.7,
    reviews: 2134,
    inStock: true,
    features: ["2K+1080p", "GPS + WiFi", "Supercapacitor", "Voice control"],
    compatibility: ["Universal - 12V/24V"],
    specifications: { "Front": "2K 30fps", "Rear": "1080p 30fps", "Storage": "256GB max", "Battery": "Supercapacitor" },
    tags: ["tech", "safety"],
    badge: "trending",
  },
  {
    id: "tb-021",
    name: "Timing Chain Kit - Complete",
    description: "Complete timing chain kit with chain, guides, tensioner, and sprockets. For engines with timing chains instead of belts.",
    price: 5499,
    originalPrice: 7499,
    category: "engine",
    subcategory: "Timing Chain",
    brand: "INA",
    images: ["/products/p21-1.svg", "/products/p21-2.svg"],
    rating: 4.5,
    reviews: 432,
    inStock: true,
    features: ["Complete kit", "Chain + guides", "Updated tensioner", "OE supplier"],
    compatibility: ["Hyundai Creta 1.5", "Kia Seltos 1.5", "Maruti Ertiga 1.5"],
    specifications: { "Type": "Timing Chain", "Links": "134", "Material": "Hardened Steel", "Warranty": "80,000 km" },
    tags: ["maintenance"],
    badge: "sale",
  },
  {
    id: "fm-022",
    name: "All-Weather Boot Mat",
    description: "Custom-fit TPE boot liner with raised edges. Protects against mud, water, and spills. Easy to clean.",
    price: 1799,
    originalPrice: 2499,
    category: "accessories",
    subcategory: "Boot Mats",
    brand: "3D Mats",
    images: ["/products/p22-1.svg", "/products/p22-2.svg"],
    rating: 4.7,
    reviews: 1876,
    inStock: true,
    features: ["Custom fit", "Raised edges", "Odorless TPE", "Anti-slip"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Harrier", "MG Hector"],
    specifications: { "Material": "TPE", "Coverage": "Full boot", "Thickness": "3mm", "Color": "Black" },
    tags: ["protection"],
    badge: "bestseller",
  },
  {
    id: "cat-023",
    name: "Performance Exhaust Header",
    description: "4-2-1 stainless steel exhaust header for improved exhaust flow. Increases mid-range torque and throttle response.",
    price: 12999,
    originalPrice: 16999,
    category: "exhaust",
    subcategory: "Headers",
    brand: "Simota",
    images: ["/products/p23-1.svg", "/products/p23-2.svg"],
    rating: 4.4,
    reviews: 298,
    inStock: true,
    features: ["4-2-1 design", "304 Stainless", "TIG welded", "Direct bolt-on"],
    compatibility: ["Maruti Swift 1.2", "Hyundai i20 1.2", "Tata Altroz 1.2"],
    specifications: { "Material": "SS304", "Design": "4-2-1", "Pipe Dia": "38mm", "Finish": "Brushed" },
    tags: ["performance"],
    badge: "trending",
  },
  {
    id: "obd-024",
    name: "Bluetooth OBD2 Scanner - Basic",
    description: "Compact ELM327-based scanner for basic diagnostics. Reads/clears codes, live data, and freeze frame via smartphone app.",
    price: 1299,
    originalPrice: 1999,
    category: "tools",
    subcategory: "OBD Scanners",
    brand: "Vgate",
    images: ["/products/p24-1.svg", "/products/p24-2.svg"],
    rating: 4.3,
    reviews: 3456,
    inStock: true,
    features: ["ELM327 v1.5", "Bluetooth 4.0", "iOS/Android", "Compact size"],
    compatibility: ["All OBD2 vehicles (2001+)"],
    specifications: { "Protocol": "OBD2/EOBD", "Chip": "ELM327", "Power": "Vehicle bus", "App": "Torque, Carista" },
    tags: ["budget", "diagnostics"],
    badge: "sale",
  },
  {
    id: "bp-025",
    name: "Rear Brake Drum Kit",
    description: "Complete rear brake drum assembly with shoes, springs, and wheel cylinder. For drum brake equipped vehicles.",
    price: 2799,
    originalPrice: 3999,
    category: "brakes",
    subcategory: "Brake Drums",
    brand: "TVS",
    images: ["/products/p25-1.svg", "/products/p25-2.svg"],
    rating: 4.5,
    reviews: 678,
    inStock: true,
    features: ["Complete kit", "OE spec shoes", "Includes springs", "Pre-adjusted"],
    compatibility: ["Maruti Alto", "WagonR", "Celerio", "Tata Tiago"],
    specifications: { "Type": "Rear Drum", "Diameter": "200mm", "Shoe Width": "35mm", "Warranty": "24 months" },
    tags: ["maintenance"],
    badge: "sale",
  },
  {
    id: "oil-026",
    name: "Gear Oil 75W-90 GL-5 (1L)",
    description: "High-performance synthetic gear oil for manual transmissions and differentials. Superior wear protection under extreme loads.",
    price: 899,
    originalPrice: 1199,
    category: "engine",
    subcategory: "Gear Oil",
    brand: "Motul",
    images: ["/products/p26-1.svg", "/products/p26-2.svg"],
    rating: 4.8,
    reviews: 1567,
    inStock: true,
    features: ["GL-5 rated", "100% Synthetic", "Shear stable", "Low temp flow"],
    compatibility: ["Manual transmissions", "Differentials", "Transfer cases"],
    specifications: { "Viscosity": "75W-90", "API": "GL-5", "Volume": "1 Liter", "Type": "Fully Synthetic" },
    tags: ["maintenance", "performance"],
    badge: "bestseller",
  },
  {
    id: "sp-027",
    name: "Ignition Coil Pack - 4 Cylinder",
    description: "Direct replacement ignition coils with improved insulation and heat resistance. Restores engine performance and fuel economy.",
    price: 3299,
    originalPrice: 4499,
    category: "electrical",
    subcategory: "Ignition Coils",
    brand: "Denso",
    images: ["/products/p27-1.svg", "/products/p27-2.svg"],
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    features: ["OE replacement", "High dielectric", "Heat resistant", "Plug & play"],
    compatibility: ["Honda City", "Jazz", "Amaze", "WR-V"],
    specifications: { "Type": "Pencil Coil", "Terminals": "4-pin", "Resistance": "0.5-1.5Ω", "Warranty": "24 months" },
    tags: ["ignition"],
    badge: "trending",
  },
  {
    id: "sa-028",
    name: "Sway Bar Link Kit - Front",
    description: "Heavy-duty stabilizer links with sealed ball joints. Reduces body roll and improves cornering stability.",
    price: 1599,
    originalPrice: 2199,
    category: "suspension",
    subcategory: "Sway Bar Links",
    brand: "Moog",
    images: ["/products/p28-1.svg", "/products/p28-2.svg"],
    rating: 4.5,
    reviews: 892,
    inStock: true,
    features: ["Sealed joints", "Greaseable", "Powder coated", "Direct fit"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Harrier", "MG Hector"],
    specifications: { "Type": "Front Link", "Length": "285mm", "Thread": "M12x1.25", "Finish": "Black phosphate" },
    tags: ["handling"],
    badge: "sale",
  },
  {
    id: "acc-029",
    name: "Car Cover - 5 Layer Outdoor",
    description: "All-weather car cover with 5-layer construction. UV resistant, waterproof, breathable, with mirror pockets and lock cable.",
    price: 2499,
    originalPrice: 3499,
    category: "accessories",
    subcategory: "Car Covers",
    brand: "AutoForm",
    images: ["/products/p29-1.svg", "/products/p29-2.svg"],
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    features: ["5-layer", "UV resistant", "Breathable", "Lock cable included"],
    compatibility: ["Sedan (4.5-4.8m)"],
    specifications: { "Layers": "5", "Material": "PP + PE + Aluminum", "Waterproof": "Yes", "Warranty": "12 months" },
    tags: ["protection"],
    badge: "bestseller",
  },
  {
    id: "bat-030",
    name: "Lithium Jump Starter 2000A",
    description: "Compact lithium jump starter with 2000A peak current. USB-C PD charging, LED flashlight, and power bank function.",
    price: 4999,
    originalPrice: 6999,
    category: "electrical",
    subcategory: "Jump Starters",
    brand: "Noco",
    images: ["/products/p30-1.svg", "/products/p30-2.svg"],
    rating: 4.8,
    reviews: 4567,
    inStock: true,
    features: ["2000A peak", "USB-C PD 60W", "LED light", "Power bank"],
    compatibility: ["Gas up to 8L", "Diesel up to 6L"],
    specifications: { "Peak Current": "2000A", "Battery": "LiFePO4", "Charging": "USB-C 60W", "Weight": "1.2 kg" },
    tags: ["emergency", "tech"],
    badge: "new",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}

export function getDiscount(price: number, originalPrice?: number): number {
  if (!originalPrice) return 0;
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  );
}

export interface FlashDeal {
  id: string;
  product: Product;
  dealPrice: number;
  dealEndsAt: string;
  maxDeals: number;
  dealsClaimed: number;
  claimedPercent: number;
}

function dealEndingIn(hours: number): string {
  return new Date(Date.now() + hours * 3600000).toISOString();
}

const flashDealProducts = [
  getProductById("bp-001")!,
  getProductById("sp-003")!,
  getProductById("hl-007")!,
  getProductById("obd-012")!,
  getProductById("dash-008")!,
  getProductById("cat-011")!,
];

export const flashDeals: FlashDeal[] = flashDealProducts.map((product, i) => ({
  id: `fd-${i + 1}`,
  product,
  dealPrice: Math.round(product.price * (i % 2 === 0 ? 0.8 : 0.75)),
  dealEndsAt: dealEndingIn(6 + i * 3),
  maxDeals: 50,
  dealsClaimed: [32, 41, 18, 27, 12, 45][i],
  claimedPercent: [64, 82, 36, 54, 24, 90][i],
}));

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  emoji: string;
  author: string;
  date: string;
  readTime: string;
}

export const blogPosts: BlogPost[] = [
  {
    id: "bp-1",
    title: "How to Choose the Right Engine Oil for Your Car",
    excerpt: "Engine oil is the lifeblood of your vehicle. Learn how to pick the right viscosity and API rating for Indian driving conditions.",
    category: "Maintenance",
    emoji: "🛢️",
    author: "Rahul Sharma",
    date: "2026-09-10",
    readTime: "5 min read",
  },
  {
    id: "bp-2",
    title: "Brake Pads vs Brake Shoes: What's the Difference?",
    excerpt: "Understanding the difference between disc and drum braking systems and how to know which one your car uses.",
    category: "Braking",
    emoji: "🛑",
    author: "Priya Patel",
    date: "2026-09-07",
    readTime: "6 min read",
  },
  {
    id: "bp-3",
    title: "Top 10 Signs Your Battery Needs Replacement",
    excerpt: "Dim headlights, slow cranking, and the check-engine light — here's how your car tells you it's time for a new battery.",
    category: "Electrical",
    emoji: "🔋",
    author: "Amit Verma",
    date: "2026-09-03",
    readTime: "4 min read",
  },
  {
    id: "bp-4",
    title: "IRL Meaning of the Check Engine Light and What to Do",
    excerpt: "Don't panic when that amber light turns on. We decode the most common causes and what to check first.",
    category: "Guides",
    emoji: "⚠️",
    author: "Rahul Sharma",
    date: "2026-08-28",
    readTime: "7 min read",
  },
  {
    id: "bp-5",
    title: "Air Filter vs Cabin Filter: Both Matter",
    excerpt: "They both filter, but they serve very different jobs. Here's why neglecting either one costs you money.",
    category: "Maintenance",
    emoji: "🌬️",
    author: "Priya Patel",
    date: "2026-08-22",
    readTime: "3 min read",
  },
  {
    id: "bp-6",
    title: "Suspension Wear: How to Spot It Before It's Late",
    excerpt: "Knocking sounds, uneven tyre wear, and a bumpy ride — spot suspension problems early and save thousands in repair bills.",
    category: "Suspension",
    emoji: "🏎️",
    author: "Amit Verma",
    date: "2026-08-15",
    readTime: "6 min read",
  },
];

export function getAllBrands(): string[] {
  return Array.from(new Set(products.map((p) => p.brand))).sort();
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand);
}

export function getNewArrivals(): Product[] {
  return products.filter(
    (p) => p.badge === "new" || p.tags.includes("new")
  );
}
