import { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "engine",
    name: "Engine Parts",
    icon: "⚙️",
    subcategories: ["Pistons", "Gaskets", "Timing Belts", "Filters", "Oil Pumps"],
    count: 245,
    gradient: "from-orange-500 to-red-600",
  },
  {
    id: "brakes",
    name: "Brake System",
    icon: "🛑",
    subcategories: ["Brake Pads", "Disc Rotors", "Brake Fluid", "Calipers"],
    count: 189,
    gradient: "from-red-500 to-pink-600",
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "⚡",
    subcategories: ["Batteries", "Alternators", "Spark Plugs", "Wiring"],
    count: 312,
    gradient: "from-yellow-500 to-amber-600",
  },
  {
    id: "suspension",
    name: "Suspension",
    icon: "🏎️",
    subcategories: ["Shock Absorbers", "Springs", "Struts", "Ball Joints"],
    count: 156,
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "body",
    name: "Body Parts",
    icon: "🚗",
    subcategories: ["Bumpers", "Mirrors", "Headlights", "Fenders"],
    count: 428,
    gradient: "from-purple-500 to-violet-600",
  },
  {
    id: "exhaust",
    name: "Exhaust System",
    icon: "💨",
    subcategories: ["Mufflers", "Catalytic Converters", "Headers", "Pipes"],
    count: 98,
    gradient: "from-gray-500 to-slate-600",
  },
  {
    id: "accessories",
    name: "Accessories",
    icon: "✨",
    subcategories: ["Seat Covers", "Floor Mats", "Phone Mounts", "Dash Cams"],
    count: 567,
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "tools",
    name: "Tools & Garage",
    icon: "🔧",
    subcategories: ["Wrenches", "Jack Stands", "OBD Scanners", "Tool Kits"],
    count: 234,
    gradient: "from-cyan-500 to-sky-600",
  },
];

export const products: Product[] = [
  {
    id: "bp-001",
    name: "Ceramic Brake Pad Set - Front",
    description: "High-performance ceramic brake pads offering superior stopping power with minimal dust. Engineered for Indian driving conditions with excellent heat dissipation.",
    price: 2499,
    originalPrice: 3499,
    category: "brakes",
    subcategory: "Brake Pads",
    brand: "Brembo",
    images: ["/products/brake-pad-1.jpg", "/products/brake-pad-2.jpg"],
    rating: 4.7,
    reviews: 1243,
    inStock: true,
    features: ["Low dust formula", "Quiet operation", "OEM fitment", "Heat resistant up to 600°C"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Tata Nexon", "Honda City"],
    specifications: { Material: "Ceramic Compound", Position: "Front", Warranty: "30,000 km", Weight: "2.8 kg" },
    tags: ["bestseller", "top-rated"],
    badge: "bestseller",
  },
  {
    id: "oil-002",
    name: "Synthetic Engine Oil 5W-40 (5L)",
    description: "Fully synthetic engine oil with advanced additive technology. Provides maximum engine protection in extreme Indian weather conditions from -20°C to 50°C.",
    price: 3299,
    originalPrice: 4199,
    category: "engine",
    subcategory: "Filters",
    brand: "Mobil",
    images: ["/products/oil-1.jpg", "/products/oil-2.jpg"],
    rating: 4.8,
    reviews: 3567,
    inStock: true,
    features: ["API SN Plus certified", "Extended drain interval", "Superior engine cleanliness", "Fuel efficient"],
    compatibility: ["Universal - Petrol & Diesel"],
    specifications: { "Viscosity": "5W-40", "Volume": "5 Liters", "Type": "Fully Synthetic", "API Rating": "SN Plus" },
    tags: ["bestseller", "must-have"],
    badge: "bestseller",
  },
  {
    id: "sp-003",
    name: "Iridium Spark Plug Pack of 4",
    description: "Premium iridium spark plugs for enhanced fuel economy and smoother engine performance. Laser-welded iridium center electrode for 2x longer life.",
    price: 1899,
    originalPrice: 2499,
    category: "electrical",
    subcategory: "Spark Plugs",
    brand: "NGK",
    images: ["/products/spark-1.jpg", "/products/spark-2.jpg"],
    rating: 4.6,
    reviews: 892,
    inStock: true,
    features: ["Iridium tip", "Better fuel economy", "Easy start", "2x lifespan"],
    compatibility: ["Maruti Swift", "Hyundai Creta", "Tata Altroz", "Kia Sonet"],
    specifications: { "Electrode": "Iridium", "Thread Size": "M14x1.25", "Reach": "26.5mm", "Gap": "1.1mm" },
    tags: ["new"],
    badge: "new",
  },
  {
    id: "sa-004",
    name: "Monotube Shock Absorber Set - Rear",
    description: "Performance monotube gas-charged shock absorbers. Precision-tuned for Indian road conditions providing comfort and handling balance.",
    price: 8999,
    originalPrice: 12999,
    category: "suspension",
    subcategory: "Shock Absorbers",
    brand: "Bilstein",
    images: ["/products/shock-1.jpg", "/products/shock-2.jpg"],
    rating: 4.5,
    reviews: 456,
    inStock: true,
    features: ["Monotube design", "Gas charged", "Temperature stable", "Direct bolt-on"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Harrier", "MG Hector"],
    specifications: { "Type": "Monotube Gas", "Position": "Rear", "Length": "450mm", "Warranty": "50,000 km" },
    tags: ["trending"],
    badge: "trending",
  },
  {
    id: "acc-005",
    name: "Premium Leather Seat Cover Set",
    description: "Hand-stitched premium Nappa leather seat covers with memory foam padding. Custom-fit design for over 50 Indian car models.",
    price: 12999,
    originalPrice: 18999,
    category: "accessories",
    subcategory: "Seat Covers",
    brand: "AutoZone",
    images: ["/products/seats-1.jpg", "/products/seats-2.jpg"],
    rating: 4.9,
    reviews: 2100,
    inStock: true,
    features: ["Nappa leather", "Memory foam", "Water resistant", "Airbag compatible"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Honda City", "Tata Nexon"],
    specifications: { "Material": "Nappa Leather", "Padding": "Memory Foam", "Fit": "Custom", "Color": "Black/Red" },
    tags: ["premium"],
    badge: "bestseller",
  },
  {
    id: "bat-006",
    name: "AMG Performance Battery 72Ah",
    description: "High-cranking power battery with advanced lead-calcium technology. Designed to handle frequent start-stop traffic in Indian cities.",
    price: 5499,
    originalPrice: 6999,
    category: "electrical",
    subcategory: "Batteries",
    brand: "Exide",
    images: ["/products/battery-1.jpg", "/products/battery-2.jpg"],
    rating: 4.4,
    reviews: 1876,
    inStock: true,
    features: ["48-month warranty", "High cranking power", "Low maintenance", "Vibration resistant"],
    compatibility: ["Universal - 12V Vehicles"],
    specifications: { "Capacity": "72Ah", "Voltage": "12V", "Warranty": "48 months", "Technology": "Lead-Calcium" },
    tags: ["bestseller"],
    badge: "bestseller",
  },
  {
    id: "hl-007",
    name: "LED Headlight Kit H4 - 12000LM",
    description: "Ultra-bright LED headlight conversion kit with Cree chips. Plug-and-play installation with CANBUS compatibility.",
    price: 4299,
    originalPrice: 5999,
    category: "body",
    subcategory: "Headlights",
    brand: "Philips",
    images: ["/products/headlight-1.jpg", "/products/headlight-2.jpg"],
    rating: 4.7,
    reviews: 934,
    inStock: true,
    features: ["12000 lumens", "6000K white", "CANBUS ready", "50,000hr lifespan"],
    compatibility: ["Universal H4 fitment"],
    specifications: { "Lumens": "12,000 LM", "Color Temp": "6000K", "Power": "30W per bulb", "Lifespan": "50,000 hours" },
    tags: ["trending", "new"],
    badge: "new",
  },
  {
    id: "dash-008",
    name: "4K WiFi Dash Cam with GPS",
    description: "Ultra HD 4K front and rear dash camera with built-in GPS, night vision, and 24/7 parking surveillance mode.",
    price: 7999,
    originalPrice: 11999,
    category: "accessories",
    subcategory: "Dash Cams",
    brand: "70mai",
    images: ["/products/dashcam-1.jpg", "/products/dashcam-2.jpg"],
    rating: 4.6,
    reviews: 1567,
    inStock: true,
    features: ["4K recording", "GPS tracking", "Night vision", "App control"],
    compatibility: ["Universal - 12V"],
    specifications: { "Resolution": "4K 30fps", "FOV": "170°", "Storage": "Up to 256GB", "Connectivity": "WiFi + GPS" },
    tags: ["trending"],
    badge: "trending",
  },
  {
    id: "tb-009",
    name: "Timing Belt Kit with Water Pump",
    description: "Complete timing belt kit including belt, tensioner, idler pulleys, and water pump. Essential for engine longevity.",
    price: 6499,
    originalPrice: 8999,
    category: "engine",
    subcategory: "Timing Belts",
    brand: "Gates",
    images: ["/products/timing-1.jpg", "/products/timing-2.jpg"],
    rating: 4.5,
    reviews: 678,
    inStock: true,
    features: ["Complete kit", "OEM quality", "HNB rubber", "100,000km service life"],
    compatibility: ["Maruti Swift", "Hyundai Verna", "Honda Amaze"],
    specifications: { "Belt Type": "Toothed", "Material": "HNB Rubber", "Water Pump": "Aluminum", "Warranty": "60,000 km" },
    tags: [],
  },
  {
    id: "fm-010",
    name: "3D Custom Floor Mat Set (4 pcs)",
    description: "Premium 3D custom-fit floor mats with high-density foam backing. Waterproof and easy to clean with anti-slip design.",
    price: 3499,
    originalPrice: 4999,
    category: "accessories",
    subcategory: "Floor Mats",
    brand: "3D Mats",
    images: ["/products/floormat-1.jpg", "/products/floormat-2.jpg"],
    rating: 4.8,
    reviews: 2345,
    inStock: true,
    features: ["Custom 3D fit", "Waterproof", "Anti-slip", "Easy to clean"],
    compatibility: ["Hyundai Creta", "Kia Seltos", "Tata Nexon"],
    specifications: { "Material": "XPE Foam", "Pieces": "4", "Waterproof": "Yes", "Color": "Black" },
    tags: ["bestseller"],
    badge: "bestseller",
  },
  {
    id: "cat-011",
    name: "Sports Catalytic Converter - BS6",
    description: "High-flow sports catalytic converter compliant with BS6 norms. Improves exhaust flow by 30% for better performance.",
    price: 15999,
    originalPrice: 19999,
    category: "exhaust",
    subcategory: "Catalytic Converters",
    brand: "Simota",
    images: ["/products/catconv-1.jpg", "/products/catconv-2.jpg"],
    rating: 4.3,
    reviews: 234,
    inStock: true,
    features: ["BS6 compliant", "High flow", "Stainless steel", "Direct replacement"],
    compatibility: ["Maruti Swift", "Hyundai i20", "Tata Altroz"],
    specifications: { "Material": "Stainless Steel 304", "Compliance": "BS6", "Flow Increase": "30%", "Warranty": "24 months" },
    tags: ["performance"],
  },
  {
    id: "obd-012",
    name: "Professional OBD2 Scanner with Live Data",
    description: "Advanced OBD2 diagnostic scanner with live data streaming, freeze frame, and I/M readiness. Bluetooth enabled with smartphone app.",
    price: 3999,
    originalPrice: 5499,
    category: "tools",
    subcategory: "OBD Scanners",
    brand: "Innova",
    images: ["/products/obd-1.jpg", "/products/obd-2.jpg"],
    rating: 4.7,
    reviews: 1123,
    inStock: true,
    features: ["Live data", "Bluetooth 5.0", "Freeze frame", "I/M readiness"],
    compatibility: ["All OBD2 vehicles (2008+)"],
    specifications: { "Protocol": "OBD2/EOBD", "Connectivity": "Bluetooth 5.0", "App": "iOS & Android", "Update": "Lifetime free" },
    tags: ["trending"],
    badge: "trending",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}

export function getDiscount(price: number, originalPrice?: number): number {
  if (!originalPrice) return 0;
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  );
}
